# Generated by Django 3.2.5 on 2021-07-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='customer',
        ),
    ]
